# check options checking
library("testthat")
library("SuperLearner")
library("tidyr")
library("dplyr")
library("tibble")

source("code/utils.R")

# set up general test opts
Sys.setenv(nab = "VRC07-523-LS", outcomes = "ic50;ic80;iip;sens1;sens2", learners = "rf;xgboost;lasso", cvtune = TRUE, cvperf = TRUE, importance_grp = "", importance_ind = "", report_name = "", return = "")
test_that("Run with multiple learners and outcomes works", {
    expect_warning(source("code/check_opts.R"), NA)
})

Sys.setenv(outcomes = "ic50", learners = "rf")
test_that("Runs with single learners and outcomes work", {
    expect_warning(source("code/check_opts.R"), NA)
})

test_that("Error messages work", {
    Sys.unsetenv("nab")
    expect_error(source("code/check_opts.R"), "Please enter at least one antibody.*", class = "shiny.silent.error")
    Sys.setenv(nab = "VRC07-523-LS")
    Sys.unsetenv("outcomes")
    expect_error(source("code/check_opts.R"), "Please enter at least one outcome.*", class = "shiny.silent.error")
    Sys.setenv(outcomes = "")
    expect_error(source("code/check_opts.R"), "Please enter at least one outcome.*", class = "shiny.silent.error")
    Sys.setenv(outcomes = "not a real outcome")
    expect_error(source("code/check_opts.R"), "You have entered one or more outcomes that are not supported.*", class = "shiny.silent.error")
    Sys.setenv(outcomes = "ic50")
    Sys.unsetenv("learners")
    expect_error(source("code/check_opts.R"), "Please enter one or more learners.*", class = "shiny.silent.error")
    Sys.setenv(learners = "glm")
    expect_error(source("code/check_opts.R"), "You have entered one or more learners that are not supported.*", class = "shiny.silent.error")
    Sys.setenv(learners = "rf")
    Sys.unsetenv("importance_grp")
    expect_warning(source("code/check_opts.R"), NA)
    Sys.setenv(importance_grp = "all")
    expect_error(source("code/check_opts.R"), "Please enter either a semicolon-separated list of supported group importance types.*", class = "shiny.silent.error")
    Sys.setenv(importance_grp = "marg")
    Sys.unsetenv("importance_ind")
    expect_warning(source("code/check_opts.R"), NA)
    Sys.setenv(importance_ind = "all")
    expect_error(source("code/check_opts.R"), "Please enter either a semicolon-separated list of supported individual importance types.*", class = "shiny.silent.error")
    Sys.setenv(importance_ind = "marg")
    Sys.unsetenv("report_name")
    expect_warning(source("code/check_opts.R"), NA)
    Sys.setenv(report_name = "non-html file")
    expect_error(source("code/check_opts.R"), "Please either enter a desired name for your report.*", class = "shiny.silent.error")
    Sys.setenv(report_name = "")
    Sys.unsetenv("return_full_sl_obj")
    expect_warning(source("code/check_opts.R"), NA)
    Sys.setenv(return_full_sl_obj = TRUE)
    Sys.unsetenv("return_analysis_dataset")
    expect_warning(source("code/check_opts.R"), NA)
})
